package day42_Exceptions;

public class ThrowsKeyWord2 {
    public static void main(String[] args) throws ArithmeticException { //doesnt handle the exception

        System.out.println("Test Started");
        System.out.println(8/0);
        System.out.println("Test Completed");













    }
}
